#!/bin/bash
set -e

# Update system
yum update -y

# Install Node.js 20
curl -fsSL https://rpm.nodesource.com/setup_20.x | bash -
yum install -y nodejs

# Install PM2 globally
npm install -g pm2

# Create application log directory
LOG_DIR="/var/log/react-node-mysql-app/backend"

mkdir -p "$LOG_DIR"

touch "$LOG_DIR/combined.log"
touch "$LOG_DIR/error.log"

chown -R root:root "$LOG_DIR"

# Configure PM2 to start on boot
pm2 startup systemd -u root --hp /root
pm2 save

# Install Amazon CloudWatch Agent
yum install -y amazon-cloudwatch-agent

# Create CloudWatch Agent configuration
cat <<EOF >/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
{
"logs": {
"logs_collected": {
"files": {
"collect_list": [
{
"file_path": "/var/log/react-node-mysql-app/backend/combined.log",
"log_group_name": "node-app-logs-backend",
"log_stream_name": "{instance_id}-combined-log",
"timestamp_format": "%Y-%m-%d %H:%M:%S"
},
{
"file_path": "/var/log/react-node-mysql-app/backend/error.log",
"log_group_name": "node-app-logs-backend",
"log_stream_name": "{instance_id}-error-log",
"timestamp_format": "%Y-%m-%d %H:%M:%S"
},
{
"file_path": "/var/log/aws/codedeploy-agent/codedeploy-agent.log",
"log_group_name": "codedeploy-agent-logs-backend",
"log_stream_name": "{instance_id}-agent-log"
},
{
"file_path": "/opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log",
"log_group_name": "codedeploy-agent-logs-backend",
"log_stream_name": "{instance_id}-codedeploy-agent-deployment-log"
},
{
"file_path": "/tmp/codedeploy-agent.update.log",
"log_group_name": "codedeploy-agent-logs-backend",
"log_stream_name": "{instance_id}-codedeploy-agent-updater-log"
}
]
}
}
}
}
EOF

# Start CloudWatch Agent
/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
-a fetch-config \
-m ec2 \
-c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json \
-s

# Install CodeDeploy Agent
yum install -y ruby wget

cd /home/ec2-user

wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install

chmod +x install

./install auto

systemctl enable codedeploy-agent
systemctl start codedeploy-agent
