#!/bin/bash
set -e

############################
# Update System
############################
yum update -y

############################
# Install NGINX
############################
yum install -y nginx

systemctl enable nginx
systemctl start nginx

############################
# Variables
############################

APP_TIER_ALB_URL="internal-app-tier-internal-alb-1849548938.ap-south-1.elb.amazonaws.com"
NGINX_CONF="/etc/nginx/nginx.conf"

############################
# Backup existing config
############################

cp $NGINX_CONF ${NGINX_CONF}.bak

############################
# Configure NGINX Reverse Proxy
############################

cat <<EOF > $NGINX_CONF

user nginx;
worker_processes auto;

error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

events {
    worker_connections 1024;
}

http {

    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    access_log /var/log/nginx/access.log;

    upstream backend {
        server ${APP_TIER_ALB_URL}:80;
    }

    server {

        listen 80;
        server_name _;

        location / {

            proxy_pass http://backend;

            proxy_http_version 1.1;

            proxy_set_header Host \$host;
            proxy_set_header X-Real-IP \$remote_addr;
            proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto \$scheme;

            proxy_set_header Upgrade \$http_upgrade;
            proxy_set_header Connection "upgrade";

        }

    }

}

EOF

############################
# Restart NGINX
############################

nginx -t
systemctl restart nginx
systemctl enable nginx

############################
# Install Amazon CloudWatch Agent
############################

yum install -y amazon-cloudwatch-agent

############################
# Create CloudWatch Configuration
############################

cat <<EOF >/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json
{
  "logs": {
    "logs_collected": {
      "files": {
        "collect_list": [

          {
            "file_path": "/var/log/nginx/access.log",
            "log_group_name": "nginx-access-logs",
            "log_stream_name": "{instance_id}-access-log"
          },

          {
            "file_path": "/var/log/nginx/error.log",
            "log_group_name": "nginx-error-logs",
            "log_stream_name": "{instance_id}-error-log"
          },

          {
            "file_path": "/var/log/aws/codedeploy-agent/codedeploy-agent.log",
            "log_group_name": "codedeploy-agent-logs-frontend",
            "log_stream_name": "{instance_id}-agent-log"
          },

          {
            "file_path": "/opt/codedeploy-agent/deployment-root/deployment-logs/codedeploy-agent-deployments.log",
            "log_group_name": "codedeploy-agent-logs-frontend",
            "log_stream_name": "{instance_id}-deployment-log"
          },

          {
            "file_path": "/tmp/codedeploy-agent.update.log",
            "log_group_name": "codedeploy-agent-logs-frontend",
            "log_stream_name": "{instance_id}-updater-log"
          }

        ]
      }
    }
  }
}
EOF

############################
# Start CloudWatch Agent
############################

/opt/aws/amazon-cloudwatch-agent/bin/amazon-cloudwatch-agent-ctl \
-a fetch-config \
-m ec2 \
-c file:/opt/aws/amazon-cloudwatch-agent/etc/amazon-cloudwatch-agent.json \
-s

############################
# Install CodeDeploy Agent
############################

yum install -y ruby wget

cd /home/ec2-user

wget https://aws-codedeploy-us-east-1.s3.us-east-1.amazonaws.com/latest/install

chmod +x install

./install auto

systemctl enable codedeploy-agent
systemctl start codedeploy-agent

############################
# Finished
############################

echo "Web Tier setup completed successfully."
